
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://www.zhaoxiaoyun.top/"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: https://www.zhaoxiaoyun.top

# Google tracking id to track your visitors

google-tracking-id: "UA-75164133-2"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Xiaoyun Zhao"
title: "Xiaoyun Zhao"
description: "Blog and website of Xiaoyun, blogging mainly for tech. Opinions expressed are mine."
keywords: "personal, jekyll, theme"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Hello, I'm Xiaoyun from Shanghai Jiao Tong University."
  - text: "Looking for a job of software development."

me-img: "/img/annezhao.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 100

paginate: 8

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "annehaha"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/intel.jpg"
    date: "Sept. 2015 - April 2016"
    description: "Intel SSG/WebRTC intern."
  - image: "/img/timeline/sjtu.jpeg"
    date: "Sept. 2014 - Today"
    description: "Shanghai Jiao Tong University, Software Engineering."
  - image: "/img/timeline/xmu.jpg"
    date: "Sept. 2010 - June 2014"
    description: "Xiamen University, Software Engineering & Economics."

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "anne89757@qq.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Xiaoyun loves music of the sea."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/anne.zhao.351"
  - title: "twitter"
    url: "https://twitter.com/anne89757"
  - title: "github"
    url: "https://github.com/annehaha"
  - title: "heart"
    url: "https://www.douban.com/people/58932917/"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'
  About: 'about'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
